### ISSUE TITLE
'blip-iframe' module is outdated on Javascript template

### ISSUE THREAD

**Issue by brbnk** [heloineto/create-blip-extension#1]
## Problem
After installing the Javascript template and running it, the application raised an exception on 'blip-iframe' module. I was only able to run the application using Typescript template.

## Solution
Comparing them, I realized that Typescript project is using a newer version of the 'blip-iframe' module. 

Typescript --> 0.0.5
Javascript --> 0.0.4

Updating the version fixed the problem

## Evidences
<img width="632" alt="image" src="https://github.com/heloineto/create-blip-extension/assets/31754622/013b74b6-35c4-403f-8fdd-a09f8bd48ac9">

I'm opening a Pull Request to fix it.

**Comment by brbnk** [comment]
[Pull Request #3](https://github.com/heloineto/create-blip-extension/pull/2) opened

**Comment by heloineto** [comment]
Thank you for reporting this issue! I've merged your pull request.
